/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  guideSidebar: [
    'intro',
    'getting-started',
    'configuration',
    'core-concepts',
    'advanced-configuration',
    'advanced-usage',
    'best-practices',
    'health-monitoring',
    'troubleshooting',
    'migration-guide',
    {
      type: 'category',
      label: 'API Reference',
      items: [{ type: 'autogenerated', dirName: 'api' }],
    },
  ],
};

module.exports = sidebars;
