/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  guideSidebar: [
    'intro',
    'getting-started',
    'agent-guide',
    'configuration',
    'core-concepts',
    'advanced-configuration',
    'advanced-usage',
    'best-practices',
    'testing',
    'worker-only-apps',
    'error-handling',
    'observability',
    'bundling',
    'security',
    'health-monitoring',
    'troubleshooting',
    'migration-guide',
    {
      type: 'category',
      label: 'API Reference',
      items: [{ type: 'autogenerated', dirName: 'api' }],
    },
  ],
};

module.exports = sidebars;
